name: CI
on:
    push:
        tags: ['v[0-9].[0-9]+.[0-9]+']
jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: 🧑‍💻 Checkout Repository
              uses: actions/checkout@v6
            - name: ☕ Setup Java
              uses: actions/setup-java@v5
              with:
                  java-version: 17
                  distribution: 'temurin'
            - name: ⛑️ Setup Gradle
              uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
            - name: 🔧 Fix Permissions
              run: chmod +x ./gradlew
            - name: 🐘 Run build with Gradle
              run: ./gradlew build
            - name: 🚀 Release
              uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
              with:
                  files: |
                      ./build/distribution/*.tar
                      ./build/distribution/*.zip
                      ./build/libs/*-standalone.jar
                      ./LICENSE
