name: CI
on:
    push:
        tags: ['v[0-9].[0-9]+.[0-9]+']
jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: 🧑‍💻 Checkout Repository
              uses: actions/checkout@v6
            - name: ☕ Setup Java
              uses: actions/setup-java@v5
              with:
                  java-version: 17
                  distribution: 'temurin'
            - name: ⛑️ Setup Gradle
              uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
            - name: 🔧 Fix Permissions
              run: chmod +x ./gradlew
            - name: 🐘 Run build with Gradle
              run: ./gradlew build
            - name: 🚀 Release
              uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
              with:
                  files: |
                      ./build/distribution/*.tar
                      ./build/distribution/*.zip
                      ./build/libs/*-standalone.jar
                      ./LICENSE
